# -- DONNÉES EXTRAITES -- #
data:
  versions:
    path: VERSIONS.yaml
    keep:
      - history

# -- PRÉ-GESTION BASIQUE DES DONNÉES CAPTURÉES -- #
handler:
  dt_last_version:
    jinjang: "{{ history }} | list | sort | last"

# -- CE QUI EST ACTUALISÉ -- #
update:
  pyproject:
    data:
      path  : pyproject.toml
      change:
        - version = dt_last_version
