# -- DONNÉES EXTRAITES -- #
data:
  allversions:
    path: about.yaml
    keep:
      - history:
        - _ : version @ dt_version ...

# -- PRÉ-GESTION DES DONNÉES CAPTURÉES -- #
handlers:
  allversions:
    build:
      - dt_version
      - ...
  last_version:
    jinjang: "{allversions} | sort | last"

# -- CE QUI EST ACTUALISÉ -- #
update:
  pyproject:
    data:
      path  : pyproject.toml
      change:
        - version = last_version
