#!/usr/bin/env python3

# ---------- #
# -- TAGS -- #
# ---------- #

TAG_TOC_PATH_ABOUT = "about"
TAG_TOC_PATH_FILES = "files"

TAG_TOC_GLOB_PATTERNS = [
    TAG_TOC_PATH_GLOB       := "glob",
    TAG_TOC_PATH_RECU_GLOB  := "r-glob",
]

TAG_TOC_PATTERN_KINDS = TAG_TOC_GLOB_PATTERNS + [
    TAG_TOC_PATH_REGEX      := "regex",
    TAG_TOC_PATH_RECU_REGEX := "r-regex",
]

TAG_TOC_PATTERN_ABBREV = {
    'g' : TAG_TOC_PATH_GLOB,
    'rg': TAG_TOC_PATH_RECU_GLOB,
    'r' : TAG_TOC_PATH_REGEX,
    'rr': TAG_TOC_PATH_RECU_REGEX
}


# ---------------- #
# -- DELIMITERS -- #
# ---------------- #

TAG_YAML_AFFILIATION_OPEN, TAG_YAML_AFFILIATION_CLOSE = "()"
TAG_YAML_EMAIL_OPEN      , TAG_YAML_EMAIL_CLOSE       = "[]"
TAG_YAML_PARTICLE_OPEN   , TAG_YAML_PARTICLE_CLOSE    = "{}"

DELIMS_EMAIL       = TAG_YAML_EMAIL_OPEN + TAG_YAML_EMAIL_CLOSE
DELIMS_AFFILIATION = TAG_YAML_AFFILIATION_OPEN + TAG_YAML_AFFILIATION_CLOSE
DELIMS_PERSON      = ["",DELIMS_EMAIL, DELIMS_AFFILIATION]

DELIMS_PARTICLE = TAG_YAML_PARTICLE_OPEN + TAG_YAML_PARTICLE_CLOSE
