# -- DONNÉES EXTRAITES -- #
data:
  about:
    path: about.yaml
    keep:
      - general:
        - desc    @ dt_desc
        - authors @ dt_devs
        - sources:
          - repository @ dt_repo

# -- CE QUI EST ACTUALISÉ -- #
update:
  pyproject:
    data:
      path  : pyproject.toml
      change:
        - tool.poetry:
          - description = dt_desc
          - repository  = dt_repo
          - authors     = dt_devs
