# -- DONNÉES EXTRAITES -- #
data:
  about: # Juste un nom...
    path: about.yaml
    keep:
      - general:
        - desc
        - authors
        - sources:
          - repository

# -- CE QUI EST ACTUALISÉ -- #
update:
  pyproject: # Juste un nom...
    data:
      path  : pyproject.toml
      change:
        - tool:
          - poetry:
            - description = desc
            - repository
            - authors
