__abrev__:
  am_data: aboutmeta.data

project*:
  version*: \am_data.version.Version

  acronym* : str
  codename*: str
  desc     : str

  authors* | author*: list(\am_data.person.Person) | \am_data.person.Person

  contribs* | contrib*: list(\am_data.person.Person) | \am_data.person.Person

  urls*:
    home*  : str
    dev*   : str
    issues*: str

  licenses*:
    code*  : \am_data.license.License
    manual*: \am_data.license.License

  langs*:
    doc*   : \am_data.lang.Lang
    manual*: \am_data.lang.Lang

  require*: list(str)

  keywords*: list(str)
