project*:
  version*: version

  acronym*            : str
  doctitle | codename*: str | str
  desc                : str

  authors | author *: list(person) | person

  contribs | contrib *: list(person) | person

  urls*:
    home*  : str
    dev*   : str
    issues*: str

  licenses*:
    code*  : license
    manual*: license

  langs*:
    doc*   : lang
    manual*: lang

  require*: list(str)

  keywords*: list(str)
