project*:
  version*: str

  acronym* : str
  codename*: str
  desc     : str

  authors* | author*: list(str) | str

  contribs* | contrib*: list(str) | str

  urls*:
    home*  : str
    dev*   : str
    issues*: str

  licenses*:
    code*  : str
    manual*: str

  langs*:
    doc*   : str
    manual*: str

  require*: list(str)

  keywords*: list(str)
