###
# This block allows to describe a project from a technical point
# of view.
###


###
# This is the current version number of the project.
###
version*: sem_version
###
# This is the date of the current version of the project.
###
date*: date
###
# This information explains the meaning of the acronym used to
# name the project.
###
acronym*: str
###
# {codename}
# This value, optional for a code-type project, allows to name
# the project differently from the folder containing it.
#
# {doctitle}
# This value is mandatory for a “document” type project: it gives
# the title of the document.
###
codename | doctitle *: .
###
# You need to describe shortly your project.
###
desc: .
###
# {author}
# For a single author, you have the following possible syntaxes.
#
#   + ''Krivine'' , ''Louis, Krivine'' and ''Jean, Louis, Krivine''
#     are legal titles for a person (the number of first names is
#     unlimited).
#
#   + ''Krivine [jlk@brain.fr]'' adds an email.
#
#   + ''Krivine (L'Institut du Cerveau, France)'' adds an
#     affiliation.
#
#   + ''Krivine [jlk@brain.fr] (L'Institut du Cerveau, France)''
#     mixes the previous features.
#
# {authors}
# For severals authors, just use a YAML list of single authors
# (see the description of the key ''author'').
###
author | authors *: person | list(.)

###
# {contrib}
# For a single contributor, the syntaxes allowed are similar to
# the ones for a single author (see the key ''author'').
#
# {contribs}
# For severals authors, just use a YAML list of single authors
# (see the description of the key ''author'').
###
contrib | contribs *: . | list(.)

###
# Three kinds of URL can be given.
#
#   + ''home'' is for the website of the project, the human one.
#
#   + ''dev'' is dedicated to the repository of the project, this
#     is not intended for human beings.
#
#   + ''issues'' allows regular users to report bugs.
###
urls*:
  home, dev, issues*: url

###
# Granting a license is a good practice.
#
#   + ''code'' is for the code of the project.
#
#   + ''manual'' is for the manual of the project.
###
licenses*:
  code, manual*: license

###
# This for the language used to write the manual (manual) and
# the technical (doc) documentations.
###
langs*:
  doc, manual*: lang

###
# Don't forget to give the list of the required general tools
# needed to make your project functional.
###
require*:
  - str

###
# Providing a list of keywords describing the project helps to
# better understand its usefulness.
###
keywords*:
  - .
